import type { Product } from '../../../types/product';

export const PRODUCT_SEEDS: Product[] = [
  {
    id: 0,
    name: 'Kids Outfit',
    description: 'A comfortable matching outfit for everyday play.',
    price: 50000,
    photo: '/product-images/kids-outfit.svg',
    category: ['KIDS', 'OUTFITS'],
    stock: 8,
  },
  {
    id: 1,
    name: 'Jeans',
    description: 'Classic denim jeans with a relaxed fit.',
    price: 15000,
    photo: '/product-images/jeans.svg',
    category: ['MEN', 'JEANS'],
    stock: 12,
  },
  {
    id: 2,
    name: 'Dress Pants',
    description: 'Lightweight dress pants for work or formal events.',
    price: 30000,
    photo: '/product-images/pants.svg',
    category: ['MEN', 'PANTS'],
    stock: 5,
  },
  {
    id: 3,
    name: 'Casual Pants',
    description: 'Everyday pants with a simple straight-leg cut.',
    price: 25000,
    photo: '/product-images/pants.svg',
    category: ['MEN', 'PANTS'],
    stock: 10,
  },
  {
    id: 4,
    name: 'Women Dress',
    description: 'A bright casual dress for warm weather.',
    price: 30000,
    photo: '/product-images/dress.svg',
    category: ['WOMEN', 'DRESSES'],
    stock: 4,
  },
  {
    id: 5,
    name: 'Green Pants',
    description: 'Soft green pants with a comfortable waist.',
    price: 10000,
    photo: '/product-images/pants.svg',
    category: ['MEN', 'PANTS'],
    stock: 0,
  },
  {
    id: 6,
    name: 'Brown Pants',
    description: 'Brown pants that pair well with casual shirts.',
    price: 20000,
    photo: '/product-images/pants.svg',
    category: ['MEN', 'PANTS'],
    stock: 7,
  },
  {
    id: 7,
    name: 'Women Top',
    description: 'A lightweight top for casual outfits.',
    price: 15000,
    photo: '/product-images/women-top.svg',
    category: ['WOMEN', 'TOPS'],
    stock: 15,
  },
  {
    id: 8,
    name: 'Girls Outfit',
    description: 'A colorful outfit set for special occasions.',
    price: 25000,
    photo: '/product-images/kids-outfit.svg',
    category: ['KIDS', 'OUTFITS'],
    stock: 3,
  },
  {
    id: 9,
    name: 'Sweatshirt',
    description: 'A cozy sweatshirt for cooler days.',
    price: 30000,
    photo: '/product-images/sweatshirt.svg',
    category: ['MEN', 'SWEATSHIRTS'],
    stock: 6,
  },
];
